[WIP] Integrate avatar with Scrimba
scrimba/discord-bot pull request #53
Opened 2021-11-19 08:59 UTC by codeluggage

Closes #29 

## Changes

WIP, not connected yet. 

- Includes a few general improvements to types that are outside of the scope of this PR
- Begins a concept of log levels throughout the bot codebase

## Open questions

- [ ] How are we organizing code from an architecture point of view, now that it's all Imba? Early intent here is to move towards classes and composition.

2021-11-19 16:54 UTC, Pistus reviewed
Had a quick first look. In general looks like a good direction.

2021-11-19 16:54 UTC, Pistus commented on src/ScrimbaIntegration.imba
> +import { log_discord, log_error, log_info } from "./utils/logger"
I think this would be better as a named import so that the calls are log.info, log.error, etc.

2021-11-23 07:56 UTC, Pistus commented
`How are we organizing code from an architecture point of view, now that it's all Imba? Early intent here is to move towards classes and composition.`

- Ok, sounds like a good start

`Would it be fun for the community to have an API to update their avatar through? Would open for challenges in the future, updating their avatar programatically.`

- Do you then mean that they can upload images or paste any link to be their avatar? This doesn't sound like great value to me.

2021-11-24 07:08 UTC, codeluggage commented
> `Would it be fun for the community to have an API to update their avatar through? Would open for challenges in the future, updating their avatar programatically.`
> 
>     * Do you then mean that they can upload images or paste any link to be their avatar? This doesn't sound like great value to me.

No, rather that it could be a "learn a little backend" part of a course. Specifically, being able to see their avatar change in the navbar as they run code. 

In any case, we're moving away from this approach and there is a simpler implementation I'm pushing up later, so we can skip this thought 👍

2021-11-29 21:50 UTC, Pistus requested changes
Some hygiene comments - the main syncing code looks good. I have failed to complete the setup of my own discord server so haven't tested it yet (have copied a template of the scrimba server, but stopped there). But I am happy to ship this as it is quite contained and the commit with the logic was easy to go through.

2021-11-29 21:50 UTC, Pistus commented on src/ScrimbaIntegration.imba
> +	def avatar_needs_refresh\Promise<string | undefined> user\User, member\GuildMember?
I got two suggestions for the naming convention here. Let's see if any of them fit:)

Number 1: A predicate ala. `refreshAvatar?`

Number 2: The camelCase version as that is the defacto standard in the repo ala. `avatarNeedsRefresh`

2021-11-29 21:50 UTC, Pistus commented on src/ScrimbaIntegration.imba
> +	def refresh_avatar\Promise<void> user\User, new_avatar\string
`update_avatar` seems more precise and consistent with discord.js + scrimba-site repo. Or `updateAvatar` if you get on the camel ride 👆

2021-11-30 07:45 UTC, codeluggage commented on src/utils/logger.imba
> +def to_channel\Promise<void> channel_source\Guild, type\string, description\string, image\string?
+1 - I'd love to do this. I have gleaned quite a bit of best practices around this from the recent investigation into posting for the users, and wrapping a class around the `Client` would set us up for simplified logging. That would also make the code more terse, as the initial creation of the logger can take in what the `type` would be, etc. 

Deferring this until we refactor the functional `onboarding.imba` and `karma.imba` files.

2021-11-30 13:41 UTC, Pistus approved these changes
Ok, logger issue to be handled later - looks good.

2021-11-30 13:51 UTC, merged